### ISSUE TITLE
IDE和手机端无法登陆，提示User not exsist

### ISSUE THREAD

**Issue by zx900930** [eritpchy/Xscript#1]
![image](https://user-images.githubusercontent.com/734749/78537059-28958c80-77ef-11ea-9c7c-2c7445c86426.png)
![image](https://user-images.githubusercontent.com/734749/78537201-61cdfc80-77ef-11ea-9fbd-6565b86d520b.png)

**Comment by eritpchy** [comment]
已正常, 再试试
