### ISSUE TITLE
免root的实现方式

### ISSUE THREAD

**Issue by zx900930** [eritpchy/Xscript#2]
实际情况：
[手游](https://play.google.com/store/apps/details?id=com.stove.epic7.google&hl=zh)禁root的同时也禁xposed
而且利用[bug](https://github.com/topjohnwu/Magisk/issues/2406)检测magisk hide
xposed是检测包名 hookMethod 和 内存objects
所以基于xposed的免root无用。

能否考虑像其它工具那样提供adb引导的免root方式？

**Comment by eritpchy** [comment]
虚拟大师

**Comment by zx900930** [comment]
> 虚拟大师

虚拟大师不支持模拟器和x86，支持模拟器还是挺重要的。

**Comment by eritpchy** [comment]
不可能每个方向都覆盖的， 做出来也没人用
如有商务合作请联系: xscript@qq.com

**Comment by zx900930** [comment]
感谢解答，我自己想想办法
